# .goreleaser.yml
project_name: moneytrack-api

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64,linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .Description }}
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses={{ .License }}

release:
  github:
    owner: "{{ index (split \"/\" .Env.GITHUB_REPOSITORY) 0 }}"
    name: "{{ index (split \"/\" .Env.GITHUB_REPOSITORY) 1 }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
