services:
    mysql:
        image: mysql:8.0
        container_name: ${DB_HOST}
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - '${DB_PORT}:3306'
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - moneytrack-network

    api:
        image: ghcr.io/panosdim/moneytrack-api:latest
        container_name: moneytrack-api
        restart: unless-stopped
        depends_on:
            - mysql
        env_file:
            - .env
        ports:
            - '${PORT}:${PORT}'
        networks:
            - moneytrack-network

volumes:
    mysql-data:

networks:
    moneytrack-network:
        driver: bridge
